IdentityServer/Controllers/AuthLoginController.cs
using IdentityModel;
using IdentityServer;
using IdentityServer.Encrypt;
using IdentityServer4;
using IdentityServer4.Events;
using IdentityServer4.Extensions;
using IdentityServer4.Models;
using IdentityServer4.Services;
using IdentityServer4.Stores;
using IdentityServer4.Validation;
using IdentityServerModel;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Security.Claims;

namespace IdentityServerHost.Quickstart.UI
{
    [SecurityHeaders]
    [AllowAnonymous]
    public class AuthLoginController : Controller
    {
        private readonly IIdentityServerInteractionService _interaction;
        private readonly IClientStore _clientStore;
        private readonly IAuthenticationSchemeProvider _schemeProvider;
        private readonly IEventService _events;
        private readonly IHttpContextAccessor _context;
        private readonly IMessageStore<LogoutMessage> _logoutMessageStore;
        private readonly IMessageStore<ErrorMessage> _errorMessageStore;
        private readonly IConsentMessageStore _consentMessageStore;
        private readonly IPersistedGrantService _grants;
        private readonly IUserSession _userSession;
        private readonly ILogger<AuthLoginController> _logger;

        public AuthLoginController(
            IIdentityServerInteractionService interaction,
            IClientStore clientStore,
            IAuthenticationSchemeProvider schemeProvider,
            IEventService events,
            IHttpContextAccessor context,
            IMessageStore<LogoutMessage> logoutMessageStore,
            IMessageStore<ErrorMessage> errorMessageStore,
            IConsentMessageStore consentMessageStore,
            IPersistedGrantService grants,
            IUserSession userSession,
            ILogger<AuthLoginController> logger)
        {
            _interaction = interaction;
            _clientStore = clientStore;
            _schemeProvider = schemeProvider;
            _events = events;
            _context = context;
            _logoutMessageStore = logoutMessageStore;
            _errorMessageStore = errorMessageStore;
            _consentMessageStore = consentMessageStore;
            _grants = grants;
            _userSession = userSession;
            _logger = logger;
        }

        public async Task<IActionResult> Index(string returnUrl = "")
        {
            string _ReturnUrl = "~/home";

            if (Request.HttpContext.User.Identity != null && Request.HttpContext.User.Identity.IsAuthenticated)
            {
                return Redirect(_ReturnUrl);
            }
            else
            {
                var vm = await BuildLoginViewModelAsync(returnUrl);
                vm.AllowRememberLogin = true;
                vm.ReturnUrl = _ReturnUrl;
                return View(vm);
            }
        }
        /// <summary>
        /// Handle postback from username/password login
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> Login([FromBody] LoginInputModelAuth model)
        public async Task<IActionResult> Index(LoginInputModel model, string button)
        {
            var context = await _interaction.GetAuthorizationContextAsync(model.ReturnUrl);
            if (button != "login")
            //if (model.Button != "login")
            {
                if (context != null)
                {
                    // if the user cancels, send a result back into IdentityServer as if they 
                    // denied the consent (even if this client does not require consent).
                    // this will send back an access denied OIDC error response to the client.
                    await _interaction.DenyAuthorizationAsync(context, AuthorizationError.AccessDenied);

                    // we can trust model.ReturnUrl since GetAuthorizationContextAsync returned non-null
                    if (context.IsNativeClient())
                    {
                        // The client is native, so this change in how to
                        // return the response is for better UX for the end user.
                        return this.LoadingPage("Redirect", model.ReturnUrl);
                    }

                    return Redirect(model.ReturnUrl);
                }
                else
                {
                    // since we don't have a valid context, then we just go back to the home page
                    return Redirect("~/");
                }
            }

            string UserPwd = EncryptsHelper.Encrypt(model.Password);
            Account user = AccountDAO.Instance.GetOneBy(t => t.UserUid == model.Username
                                && t.Password == UserPwd);
            string message = "用户名或者密码不正确。";
            bool isfail = false;
            if (user == null) isfail = true;
            if (user != null)
            {
                if (user.IsEnable == 0)
                {
                    message = "用户信息被禁用。";
                    isfail = true;
                }
                if (user.IsDelete == 0)
                {
                    message = "用户信息不存在。";
                    isfail = true;
                }
                if (!isfail)
                {
                    isfail = false;
                    user.LoginCount++;
                    user.OnlineState = 1;
                    user.LastLoginTime = DateTime.Now.ToDateTimeString();
                    var _1 = Task.Run(() =>
                     {
                         AccountDAO.Instance.UpdateColumns(user, it => new
                         {
                             it.OnlineState,
                             it.LastLoginTime,
                             it.LoginCount,
                         });
                     });

                    await _events.RaiseAsync(new UserLoginSuccessEvent(user.UserUid, user.UserSnowId.ToString(), user.TrueName, clientId: context?.Client.ClientId));

                    AuthenticationProperties props = null;
                    if (AccountOptions.AllowRememberLogin && model.RememberLogin)
                    {
                        props = new AuthenticationProperties
                        {
                            IsPersistent = true,
                            ExpiresUtc = DateTimeOffset.UtcNow.Add(AccountOptions.RememberMeLoginDuration)
                        };
                    };

                    var additionalLocalClaims = new List<Claim>();
                    additionalLocalClaims.Add(new Claim(JwtClaimTypes.AuthenticationMethod, "AAAAApwd"));
                    additionalLocalClaims.Add(new Claim("sourcetype", "Web"));
                    string TokenLifeTime = "3600";
                    if (context != null)
                    {
                        TokenLifeTime = context.Client.AccessTokenLifetime.ToString();
                    }
                    additionalLocalClaims.Add(new Claim("tokenlifetime", TokenLifeTime));

                    var isuser = new IdentityServerUser(user.UserSnowId.ToString())
                    {
                        DisplayName = user.TrueName,
                        AdditionalClaims = additionalLocalClaims
                    };

                    await HttpContext.SignInAsync(isuser, props);

                    if (context != null)
                    {
                        if (context.IsNativeClient())
                        {
                            return this.LoadingPage("Redirect", model.ReturnUrl);
                        }

                        return Redirect(model.ReturnUrl);
                    }

                    if (Url.IsLocalUrl(model.ReturnUrl))
                    {
                        return Redirect(model.ReturnUrl);
                    }
                    else
                    {
                        if (string.IsNullOrEmpty(model.ReturnUrl))
                        {
                            return Redirect("~/");
                        }
                        else
                        {
                            return Redirect(model.ReturnUrl);
                        }
                    }
                }
            }

            if (isfail)
            {
                await _events.RaiseAsync(new UserLoginFailureEvent(model.Username, message));
                ModelState.AddModelError(string.Empty, message);
                var err = await BuildLoginViewModelAsync(model);
                return View(err);
            }
            var vm = await BuildLoginViewModelAsync(model);
            return View(vm);
        }


        /// <summary>
        /// Show logout page
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> Logout(string logoutId)
        {
            //建立一个模型，以便注销页面知道要显示什么
            var vmm = await BuildLogoutViewModelAsync(logoutId);

            if (vmm.ShowLogoutPrompt == false)
            {
                //如果从IdentityServer正确验证了注销请求，则不需要显示提示，只需直接将用户注销即可。
                return await Logout(vmm);
            }
            else
            {
                var vm = await BuildLoggedOutViewModelAsync(logoutId);

                if (User?.Identity.IsAuthenticated == true)
                {
                    // delete local authentication cookie
                    await HttpContext.SignOutAsync();

                    // raise the logout event
                    await _events.RaiseAsync(new UserLogoutSuccessEvent(User.GetSubjectId(), User.GetDisplayName()));

                    long _UserSnowId = User.GetSubjectId().ToLong();
                    Account user = AccountDAO.Instance.GetOneBy(t => t.UserSnowId == _UserSnowId);
                    if (user != null)
                    {
                        user.OnlineState = 0;
                        user.LastOutTime = DateTime.Now.ToDateTimeString(); ;

IdentityServer/Views/AuthLogin/Consent.cshtml
@model ConsentViewModel

<div class="page-consent">
    <div class="lead">
        @if (Model.ClientLogoUrl != null)
        {
            <div class="client-logo"><img src="@Model.ClientLogoUrl"></div>
        }
        <h1>
            @Model.ClientName
            <small class="text-muted">正在请求您的许可</small>
        </h1>
        <p>取消您不希望授予的权限。</p>
    </div>

    <div class="row">
        <div class="col-sm-8">
            <partial name="_ValidationSummary" />
        </div>
    </div>

    <form asp-action="Consent">
        <input type="hidden" asp-for="ReturnUrl" />
        <div class="row">
            <div class="col-sm-8">
                @if (Model.IdentityScopes.Any())
                {
                    <div class="form-group">
                        <div class="card">
                            <div class="card-header">
                                <span class="glyphicon glyphicon-user"></span>
                                个人信息
                            </div>
                            <ul class="list-group list-group-flush">
                                @foreach (var scope in Model.IdentityScopes)
                                {
                                    <partial name="_ScopeListItem" model="@scope" />
                                }
                            </ul>
                        </div>
                    </div>
                }

                @if (Model.ApiScopes.Any())
                {
                    <div class="form-group">
                        <div class="card">
                            <div class="card-header">
                                <span class="glyphicon glyphicon-tasks"></span>
                                访问应用程序
                            </div>
                            <ul class="list-group list-group-flush">
                                @foreach (var scope in Model.ApiScopes)
                                {
                                    <partial name="_ScopeListItem" model="scope" />
                                }
                            </ul>
                        </div>
                    </div>
                }

                <div class="form-group">
                    <div class="card">
                        <div class="card-header">
                            <span class="glyphicon glyphicon-tasks"></span>
                            说明
                        </div>
                        <div class="card-body">
                            <input class="form-control" placeholder="说明或名称" asp-for="Description" autofocus>
                        </div>
                    </div>
                </div>

                @if (Model.AllowRememberConsent)
                {
                    <div class="form-group">
                        <div class="form-check">
                            <input class="form-check-input" asp-for="RememberConsent">
                            <label class="form-check-label" asp-for="RememberConsent">
                                <strong>记住我的决定</strong>
                            </label>
                        </div>
                    </div>
                }
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4">
                <button name="button" value="yes" class="btn btn-primary" autofocus>是，允许</button>
                <button name="button" value="no" class="btn btn-secondary">否，不允许</button>
            </div>
            <div class="col-sm-4 col-lg-auto">
                @if (Model.ClientUrl != null)
                {
                    <a class="btn btn-outline-info" href="@Model.ClientUrl">
                        <span class="glyphicon glyphicon-info-sign"></span>
                        <strong>@Model.ClientName</strong>
                    </a>
                }
            </div>
        </div>
    </form>
</div>

IdentityServer/Views/AuthLogin/Index.cshtml
@model LoginViewModel;
@{
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<link href="~/css/login.css" rel="stylesheet" />

@if (Model.EnableLocalLogin)
{
    <div id="app">
        <div class="background">
            <div class="login-form">
                <form asp-controller="AuthLogin" asp-action="Index" method="post">
                    <input id="returnurl" type="hidden" asp-for="ReturnUrl" />

                    <div class="login-logo-div">
                        <img class="login-logo" src="~/logo.png" alt="logo" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Username">用户：</label>
                        <input id="username" class="form-control" asp-for="Username" placeholder="请输入用户名" value="superadmin" type="text" autofocus>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password">密码：</label>
                        <div class="input-group">
                            <input id="password" type="password" class="form-control" asp-for="Password" value="super147" placeholder="请输入密码">
                            <div class="input-icon">
                                <input type="checkbox" class="show-password" id="showPasswordCheckbox">
                                <label for="showPasswordCheckbox" class="show-hidden">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 20 20">
                                        <path fill="currentColor"
                                              d="M3.26 11.602C3.942 8.327 6.793 6 10 6s6.057 2.327 6.74 5.602a.5.5 0 0 0 .98-.204C16.943 7.673 13.693 5 10 5s-6.943 2.673-7.72 6.398a.5.5 0 0 0 .98.204M9.99 8a3.5 3.5 0 1 1 0 7a3.5 3.5 0 0 1 0-7" />
                                    </svg>
                                </label>
                            </div>
                        </div>
                    </div>
                    @if (Model.AllowRememberLogin)
                    {
                        <div class="form-check login-form-remember">
                            <input class="form-check-input" type="checkbox" id="isRemember" asp-for="RememberLogin">
                            <label class="form-check-label" for="isRemember">
                                记住账号
                            </label>
                        </div>
                    }
                    <button class="btn btn-primary  login-form-button" name="button" id="login" value="login">登录</button>
                    <button class="btn btn-secondary  login-form-button" name="button" value="cancel">取消</button>
                    <div class="login-valid ">
                        <partial name="_ValidationSummary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
}

<script src="~/js/login.js"></script>

IdentityServer/Views/AuthLogin/Logout.cshtml
@model LogoutViewModel

<div class="logout-page">
    <div class="lead">
        <h1>确定退出?</h1>
    </div>

    <form asp-action="Logout">
        <input type="hidden" name="logoutId" value="@Model.LogoutId"  />
        <div class="form-group">
            <button class="btn btn-primary">确定</button>
        </div>
    </form>
</div>